version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apapesc_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Porta do host para evitar conflito
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy  # Espera o PostgreSQL estar pronto
    ports:
      - "80:8000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/apapesc_db

volumes:
  postgres_data:
