# Generated by Django 5.1.3 on 2024-11-14 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0015_alter_associadomodel_ctps_uf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('arquivo', models.FileField(upload_to='documentos/', verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_associados.associadomodel', verbose_name='Associado')),
            ],
        ),
    ]
