# Generated by Django 5.1.3 on 2024-11-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_doc',
            field=models.CharField(choices=[('CNIS Cadastro Nac. de Infos Sociais', 'CNIS Cadastro Nac. de Infos Sociais'), ('CPF', 'CPF'), ('Carteira de Trabalho CTPS', 'Carteira de Trabalho CTPS'), ('Carta de Concessão aposentados/pensionistas', 'Carta de Concessão aposentados/pensionistas'), ('Foto 3x4', 'Foto 3x4'), ('Habilitação CHN', 'Habilitação CHN'), ('Histórico de Créditode Benefício', 'Histórico de Créditode Benefício'), ('INSS Extrato de Contribuições', 'INSS Extrato de Contribuições'), ('Dar outro nome', 'Dar outro nome'), ('Protocolo pedido Licença Embarcação', 'Protocolo pedido Licença Embarcação'), ('Protocolo pedido RGP', 'Protocolo pedido RGP'), ('Registro de Pescador RGP', 'Registro de Pescador RGP'), ('RG', 'RG')], default='Outros', max_length=100, verbose_name='Tipo do Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Documento'),
        ),
    ]
