# Generated by Django 5.1.3 on 2024-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApapescModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('fundadores', models.TextField(help_text='Lista de fundadores da associação', verbose_name='Fundadores')),
                ('diretor', models.CharField(max_length=255, verbose_name='Diretor')),
                ('administrador', models.CharField(max_length=255, verbose_name='Administrador')),
                ('presidente', models.CharField(max_length=255, verbose_name='Presidente')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Apapesc',
                'ordering': ['nome_fantasia'],
            },
        ),
    ]
