# Generated by Django 5.1.3 on 2024-11-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0004_alter_associadomodel_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associadomodel',
            name='localidade_atuacao',
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='localidade_apapesc',
            field=models.CharField(blank=True, choices=[('Florianópolis', 'Florianópolis'), ('Balneário', 'Balneário'), ('Garopaba', 'Garopaba'), ('Laguna', 'Laguna'), ('Itapema', 'Itapema'), ('Itajai', 'Itajai'), ('Imbituba', 'Imbituba'), ('São Francisco do Sul', 'São Francisco do Sul'), ('Joinville', 'Joinville'), ('Porto Belo', 'Porto Belo'), ('Palhoça', 'Palhoça')], max_length=40, null=True, verbose_name='Localidade Apapesc'),
        ),
    ]
