# Generated by Django 5.1.3 on 2024-11-12 19:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0008_associadomodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo(a)', 'Ativo(a)'), ('Aposentado(a)', 'Aposentado(a)')], default='Ativo(a)', max_length=40, null=True, verbose_name='Status'),
        ),
    ]
