# Generated by Django 5.1.3 on 2024-11-13 00:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0009_alter_associadomodel_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='sexo_biologico',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('SexoBio', 'SexoBio')], default='SexoBio', max_length=10, null=True, verbose_name='Sexo Biológico'),
        ),
    ]
