# Generated by Django 5.1.3 on 2024-11-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0013_municipioscircusnscricaomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='municipio_circunscricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associados', to='app_associados.municipioscircusnscricaomodel', verbose_name='Município de Circunscrição'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='reparticao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associados', to='app_associados.reparticaomodel', verbose_name='Nome da Repartição'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='sexo_biologico',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=15, verbose_name='Sexo Biológico'),
        ),
    ]
