# Generated by Django 5.1.3 on 2024-11-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0016_associadomodel_especie1_associadomodel_especie2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='especie1',
            field=models.CharField(blank=True, choices=[('Pampo', 'Pampo'), ('Abrótea', 'Abrótea'), ('Tainha', 'Tainha'), ('Anchova', 'Anchova'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Atum', 'Atum'), ('Corvina', 'Corvina'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Linguado', 'Linguado'), ('Garoupa', 'Garoupa'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cavala', 'Cavala'), ('Xerelete', 'Xerelete'), ('Cação', 'Cação'), ('Marisco', 'Marisco'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 1'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie2',
            field=models.CharField(blank=True, choices=[('Pampo', 'Pampo'), ('Abrótea', 'Abrótea'), ('Tainha', 'Tainha'), ('Anchova', 'Anchova'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Atum', 'Atum'), ('Corvina', 'Corvina'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Linguado', 'Linguado'), ('Garoupa', 'Garoupa'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cavala', 'Cavala'), ('Xerelete', 'Xerelete'), ('Cação', 'Cação'), ('Marisco', 'Marisco'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 2'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie3',
            field=models.CharField(blank=True, choices=[('Pampo', 'Pampo'), ('Abrótea', 'Abrótea'), ('Tainha', 'Tainha'), ('Anchova', 'Anchova'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Atum', 'Atum'), ('Corvina', 'Corvina'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Linguado', 'Linguado'), ('Garoupa', 'Garoupa'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cavala', 'Cavala'), ('Xerelete', 'Xerelete'), ('Cação', 'Cação'), ('Marisco', 'Marisco'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 3'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie4',
            field=models.CharField(blank=True, choices=[('Pampo', 'Pampo'), ('Abrótea', 'Abrótea'), ('Tainha', 'Tainha'), ('Anchova', 'Anchova'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Atum', 'Atum'), ('Corvina', 'Corvina'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Linguado', 'Linguado'), ('Garoupa', 'Garoupa'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cavala', 'Cavala'), ('Xerelete', 'Xerelete'), ('Cação', 'Cação'), ('Marisco', 'Marisco'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 4'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='especie5',
            field=models.CharField(blank=True, choices=[('Pampo', 'Pampo'), ('Abrótea', 'Abrótea'), ('Tainha', 'Tainha'), ('Anchova', 'Anchova'), ('Robalo', 'Robalo'), ('Sardinha', 'Sardinha'), ('Atum', 'Atum'), ('Corvina', 'Corvina'), ('Pescada-olhuda', 'Pescada-olhuda'), ('Linguado', 'Linguado'), ('Garoupa', 'Garoupa'), ('Bagre', 'Bagre'), ('Baiacu', 'Baiacu'), ('Cavala', 'Cavala'), ('Xerelete', 'Xerelete'), ('Cação', 'Cação'), ('Marisco', 'Marisco'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Espécie 5'),
        ),
    ]
