# Generated by Django 5.1.3 on 2024-11-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0017_alter_associadomodel_especie1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viúvo', 'Viúvo'), ('União Estável', 'União Estável'), ('Separado Judicialmente', 'Separado Judicialmente'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True, verbose_name='Estado Civil'),
        ),
    ]
