# Generated by Django 5.1.3 on 2024-11-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0019_alter_associadomodel_ctps_uf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='profissao',
            field=models.CharField(blank=True, choices=[('Pescador Profissional', 'Pescador Profissional'), ('Pescadora Profissional', 'Pescadora Profissional'), ('Aposentado', 'Aposentado'), ('Aposentada', 'Aposentada'), ('Profissional Autônomo', 'Profissional Autônomo'), ('Empresário', 'Empresário'), ('Empresária', 'Empresária'), ('Comerciante', 'Comerciante'), ('Professor', 'Professor'), ('Professora', 'Professora'), ('Trabalhador Doméstico', 'Trabalhador Doméstico'), ('Gari', 'Gari'), ('Servidor Público', 'Servidor Público'), ('Micro Empreendedor Individual', 'Micro Empreendedor Individual'), ('Não declarado', 'Não declarado')], default='Nao declarado', max_length=50, null=True),
        ),
    ]
