# Generated by Django 5.1.3 on 2024-11-17 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0021_alter_associadomodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='quantidade1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade 1 (Kg)'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='quantidade2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade 2 (Kg)'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='quantidade3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade 3 (Kg)'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='quantidade4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade 4 (Kg)'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='quantidade5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade 5 (Kg)'),
        ),
    ]
