# Generated by Django 5.1.3 on 2024-11-18 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0023_rename_celular_delegado_reparticaomodel_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associadomodel',
            name='celular_correspondencia',
            field=models.CharField(default='(00)00000-0000', max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\d{5}-\\d{4}$', 'Número inválido. O telefone deve conter 10 ou 11 dígitos, ex: (48)99999-9999.')]),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='escolaridade',
            field=models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Primário 1/4 série', 'Primário 1/4 série'), ('Fundamental', 'Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Ensino Superior', 'Ensino Superior'), ('NÃO_DECLARADO', 'Não declarado')], default='Não declarado', max_length=20, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='etnia',
            field=models.CharField(choices=[('BRANCO', 'Branco'), ('PARDO', 'Pardo'), ('PRETO', 'Preto'), ('AMARELO', 'Amarelo'), ('INDÍGENA', 'Indígena'), ('OUTRO', 'Outro'), ('NÃO_DECLARADO', 'Não declarado')], default='Não declarado', max_length=15, verbose_name='Etnia'),
        ),
        migrations.AddField(
            model_name='associadomodel',
            name='recolhe_inss',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não declarado', 'Não declarado')], default='Nao declarado', max_length=50, null=True),
        ),
    ]
