# Generated by Django 5.1.3 on 2024-11-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0025_alter_associadomodel_celular_correspondencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='escolaridade',
            field=models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('Primário 1/4 série', 'Primário 1/4 série'), ('Fundamental', 'Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Ensino Superior', 'Ensino Superior'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=20, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='etnia',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Pardo', 'Pardo'), ('Preto', 'Preto'), ('Amarelo', 'Amarelo'), ('Indígena', 'Indígena'), ('Outro', 'Outro'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=15, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='profissao',
            field=models.CharField(blank=True, choices=[('Pescador Profissional', 'Pescador Profissional'), ('Pescadora Profissional', 'Pescadora Profissional'), ('Aposentado', 'Aposentado'), ('Aposentada', 'Aposentada'), ('Profissional Autônomo', 'Profissional Autônomo'), ('Empresário', 'Empresário'), ('Empresária', 'Empresária'), ('Comerciante', 'Comerciante'), ('Professor', 'Professor'), ('Professora', 'Professora'), ('Trabalhador Doméstico', 'Trabalhador Doméstico'), ('Gari', 'Gari'), ('Servidor Público', 'Servidor Público'), ('Micro Empreendedor Individual', 'Micro Empreendedor Individual'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='associadomodel',
            name='recolhe_inss',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não declarado', 'Não declarado')], default='Não declarado', max_length=50, null=True),
        ),
    ]
